endpoint:
  matchers:
    - matcher:
        post: /api/v1/mentees, /api/v1/mentors
      role: all
    - matcher:
        get: /api/v1/mentors/*
        post:
        put:
        patch:
        delete:
      role: user
    - matcher:
        get: /api/v1/mentors/*
        post: /api/v1/events
        put:
        patch: /api/v1/events/*, /api/v1/events/*/mentee/*
        delete:
      role: mentor
    - matcher:
        get: /api/v1/mentee/*
      role: own_mentee
  ignores: /docs/**
